-- Backfill stocktake_visible + stocktake_day_of_week from master TSV (generated).
-- Apply after 032. Updates all locations by product name match.

UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Onion peeled'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Tomato'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Flaxseed broken'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Red onion sliced fine'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Red cabbage shredded'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Coriander'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Parsley'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Cucumber'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Green lentils'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Carrot julienne'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Mint'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Green chili'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Aubergine'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Romaine lettuce'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Pomegranate seeds'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Garlic puree'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Eggs'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Garlic peeled'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Celery brunoise'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Chickpeas'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Red lentils'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Chicken'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Pita bread 15 cm'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Whole wheat pita bread 15 cm'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Feta cheese'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Greek yoghurt 10%'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Tomato puree'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Oat drink barista'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Vanilla extract'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Rice flour'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Middle Eastern pickles'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Sunflower oil'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('MSG (Ve Tsin)'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Stock'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Eggplant puree'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Kalamata olives'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Lemon juice'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Coca Cola'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Coca Cola Zero'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('SOOF Mint'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('SOOF Cardamom'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('SOOF Lavender'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Sparkling water'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Still water'));
UPDATE raw_ingredients SET stocktake_visible = FALSE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Hand soap'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('All purpose flour'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Baking powder'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Baking soda'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Cumin'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Za''atar'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Turmeric'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Black pepper'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Chili powder'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Cardamom'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Sumac'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Mustard powder'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Salt'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Sugar white'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Sugar brown'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Tahini'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Vinegar'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Flatbread'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Rice basmati'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Bulgur'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Olive oil'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Paper bags large'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Lids (bowl)'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Lids (pita)'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Paper bags small'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Rolling paper'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Paper bag (brownies)'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Pita pouches'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Mezze container'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Mezze lids'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Sauce cup'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Sauce lid'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Falafel container'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Pita container'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Bowl container'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Catering container'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Cutlery'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Stirrer'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Coffee cup'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Coffee lids'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Napkins'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Soup container'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Soup lids'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Aluminium foil'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Clingfilm'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Microfiber cloth'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Centerfeed paper roll'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Toiletpaper'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Gloves small'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Gloves medium'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Gloves large'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Daysticker Monday'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Daysticker Tuesday'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Daysticker Wednesday'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Daysticker Thursday'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Daysticker Friday'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Daysticker Saturday'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Daysticker Sunday'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Aluminium foil dispenser'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = 1 WHERE lower(btrim(name)) = lower(btrim('Flatbreadchips bags with window'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Shifka peppers'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Mango'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Cacao powder'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Coriander (fresh)'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Cauliflower'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Yoghurt'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Rice pandan'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Rose petals'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Dried dill'));
UPDATE raw_ingredients SET stocktake_visible = TRUE, stocktake_day_of_week = NULL WHERE lower(btrim(name)) = lower(btrim('Xantana'));
