-- Align stocktake list order with docs/stocktake-order-template.csv (prep + raw).
-- Prep: location_prep_items.display_order (×10, same scale as drag-reorder in app).
-- Raw: raw_ingredients.stocktake_display_order. When all were 0, the UI fell back to name sort.

UPDATE location_prep_items lpi
SET display_order = m.ord * 10, updated_at = NOW()
FROM prep_items pi
INNER JOIN (
  VALUES
    ('Marinated chicken', 1),
    ('Falafel', 2),
    ('Coated Cauliflower', 3),
    ('Aubergine / Sabich', 4),
    ('Lettuce', 5),
    ('Defrosted flatbread', 6),
    ('Regular pita with za''atar', 7),
    ('Wholewheat pita with za''atar', 8),
    ('Mediterranean salad / Medi salad', 9),
    ('Hummus', 10),
    ('Pickled onion', 11),
    ('Pickled cabbage', 12),
    ('Tzatziki', 13),
    ('Amba', 14),
    ('Tarator', 15),
    ('Srug', 16),
    ('Babe ghanouj', 17),
    ('Boiled eggs', 18),
    ('Pomegranate', 19),
    ('Feta', 20),
    ('Shifka peppers', 21),
    ('Mediterranean pickles', 22),
    ('Mint', 23),
    ('Parsley', 24),
    ('Rose lemonade', 25),
    ('Tahin brownie dough', 26),
    ('Za''atar flatbread chips', 27),
    ('Lebanese lentil soup', 28),
    ('Mudardara', 29),
    ('Turmeric rice', 30),
    ('Chicken marinade', 31),
    ('Pickling liquid', 32)
) AS m(name, ord) ON lower(trim(pi.name)) = lower(trim(m.name))
WHERE lpi.prep_item_id = pi.id;

UPDATE raw_ingredients ri
SET stocktake_display_order = m.ord * 10, updated_at = NOW()
FROM (
  VALUES
    ('All purpose flour', 33),
    ('Baking powder', 34),
    ('Baking soda', 35),
    ('Bulgur', 36),
    ('Chickpeas', 37),
    ('Green lentils', 38),
    ('Red lentils', 39),
    ('Rice basmati', 40),
    ('Rice pandan', 41),
    ('Rice flour', 42),
    ('Eggs', 43),
    ('Salt', 44),
    ('Stock', 45),
    ('Sugar brown', 46),
    ('Sugar white', 47),
    ('Tomato puree', 48),
    ('Vanilla extract', 49),
    ('Flaxseed broken', 50),
    ('Cacao powder', 51),
    ('MSG (Ve Tsin)', 52),
    ('Chili powder', 53),
    ('Coriander', 54),
    ('Cumin', 55),
    ('Black pepper', 56),
    ('Cardamom', 57),
    ('Mustard powder', 58),
    ('Sumac', 59),
    ('Turmeric', 60),
    ('Za''atar', 61),
    ('Cucumber', 62),
    ('Carrot julienne', 63),
    ('Celery brunoise', 64),
    ('Aubergine', 65),
    ('Garlic peeled', 66),
    ('Garlic puree', 67),
    ('Greek yoghurt 10%', 68),
    ('Mint', 69),
    ('Coriander (fresh)', 70),
    ('Pomegranate seeds', 71),
    ('Red cabbage shredded', 72),
    ('Red onion sliced fine', 73),
    ('Romaine lettuce', 74),
    ('Onion peeled', 75),
    ('Tomato', 76),
    ('Parsley', 77),
    ('Green chili', 78),
    ('Chicken', 79),
    ('Feta cheese', 80),
    ('Yoghurt', 81),
    ('Coca Cola', 82),
    ('Coca Cola Zero', 83),
    ('SOOF Cardamom', 84),
    ('SOOF Lavender', 85),
    ('SOOF Mint', 86),
    ('Sparkling water', 87),
    ('Still water', 88),
    ('Flatbread', 89),
    ('Pita bread 15 cm', 90),
    ('Whole wheat pita bread 15 cm', 91),
    ('Cauliflower', 92),
    ('Mango', 93),
    ('Eggplant puree', 94),
    ('Shifka peppers', 95),
    ('Middle Eastern pickles', 96),
    ('Tahini', 97),
    ('Kalamata olives', 98),
    ('Lemon juice', 99),
    ('Olive oil', 100),
    ('Sunflower oil', 101),
    ('Vinegar', 102),
    ('Oat drink barista', 103),
    ('Aluminium foil', 104),
    ('Aluminium foil dispenser', 105),
    ('Bowl container', 106),
    ('Catering container', 107),
    ('Centerfeed paper roll', 108),
    ('Clingfilm', 109),
    ('Coffee cup', 110),
    ('Coffee lids', 111),
    ('Cutlery', 112),
    ('Falafel container', 113),
    ('Flatbreadchips bags with window', 114),
    ('Gloves large', 115),
    ('Gloves medium', 116),
    ('Gloves small', 117),
    ('Hand soap', 118),
    ('Lids (bowl)', 119),
    ('Lids (pita)', 120),
    ('Mezze container', 121),
    ('Mezze lids', 122),
    ('Microfiber cloth', 123),
    ('Napkins', 124),
    ('Paper bag (brownies)', 125),
    ('Paper bags large', 126),
    ('Paper bags small', 127),
    ('Pita container', 128),
    ('Pita pouches', 129),
    ('Rolling paper', 130),
    ('Sauce cup', 131),
    ('Sauce lid', 132),
    ('Soup container', 133),
    ('Soup lids', 134),
    ('Stirrer', 135),
    ('Toiletpaper', 136),
    ('Daysticker Friday', 137),
    ('Daysticker Monday', 138),
    ('Daysticker Saturday', 139),
    ('Daysticker Sunday', 140),
    ('Daysticker Thursday', 141),
    ('Daysticker Tuesday', 142),
    ('Daysticker Wednesday', 143)
) AS m(name, ord)
WHERE lower(trim(ri.name)) = lower(trim(m.name));
